"""
macOS UI event backend.

Input comes from a listen-only CGEventTap (needs Input Monitoring).
Element lookups use AXUIElement (needs Accessibility).

The tap callback runs with the GIL held on the tap thread. It must stay tiny:
it only builds a RawEvent and puts it on the queue. If the callback is slow,
macOS disables the tap (kCGEventTapDisabledByTimeout); we turn it back on.
"""

import logging
import queue
import threading
import time
from typing import Optional

from screenmind.capture.ui_events.base import FrontWindow, PermissionStatus, UiEventBackend
from screenmind.capture.ui_events.models import (
    ElementInfo,
    KEY_ARROW,
    KEY_BACKSPACE,
    KEY_CHAR,
    KEY_ENTER,
    KEY_ESCAPE,
    KEY_OTHER,
    KEY_TAB,
    RawEvent,
)

logger = logging.getLogger("screenmind.capture.ui_events.macos")

# Virtual key codes (Carbon HIToolbox/Events.h)
_KEYCODE_MAP = {
    36: KEY_ENTER, 76: KEY_ENTER,
    48: KEY_TAB,
    51: KEY_BACKSPACE,
    53: KEY_ESCAPE,
    # arrows, home/end, page up/down, forward delete: cursor moves or
    # text changes we cannot follow
    123: KEY_ARROW, 124: KEY_ARROW, 125: KEY_ARROW, 126: KEY_ARROW,
    115: KEY_ARROW, 119: KEY_ARROW, 116: KEY_ARROW, 121: KEY_ARROW, 117: KEY_ARROW,
}

_TAP_DISABLED_BY_TIMEOUT = 0xFFFFFFFE
_TAP_DISABLED_BY_USER_INPUT = 0xFFFFFFFF

# Pasteboard types that password managers use to mark secrets.
# See http://nspasteboard.org
_SECRET_PASTEBOARD_TYPES = {
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
}

# When a click lands on a label or image inside one of these, report the
# control rather than the label.
_ACTIONABLE_ROLES = {
    "AXButton", "AXLink", "AXMenuItem", "AXMenuBarItem", "AXCheckBox",
    "AXRadioButton", "AXTab", "AXPopUpButton", "AXMenuButton", "AXDisclosureTriangle",
    "AXTextField", "AXTextArea", "AXSearchField", "AXComboBox",
}

_MAX_VALUE_LEN = 200
_MAX_NAME_LEN = 100

# Layout containers. Browsers put the whole page text into their
# AXDescription, which is noise as a click target name.
_CONTAINER_ROLES = {
    "AXGroup", "AXScrollArea", "AXWebArea", "AXSplitGroup", "AXLayoutArea",
    "AXList", "AXOutline", "AXTable", "AXUnknown", "AXWindow", "AXApplication",
}
_MAX_CONTAINER_NAME_LEN = 60

_TEXT_INPUT_ROLES = {"AXTextField", "AXTextArea", "AXComboBox", "AXSearchField"}


class MacOSUiEventBackend(UiEventBackend):
    name = "macos"

    def __init__(self):
        import ApplicationServices as AS  # type: ignore
        import Quartz  # type: ignore

        self._AS = AS
        self._Q = Quartz
        self._system_wide = AS.AXUIElementCreateSystemWide()
        # Global AX timeout: a hung app must not block the enricher for 6s.
        AS.AXUIElementSetMessagingTimeout(self._system_wide, 0.25)

        self._thread: Optional[threading.Thread] = None
        self._run_loop = None
        self._tap = None
        self._out: Optional[queue.SimpleQueue] = None

    # ── Permissions ──────────────────────────────────────────────────

    def check_permissions(self) -> PermissionStatus:
        return PermissionStatus(
            input_monitoring=bool(self._Q.CGPreflightListenEventAccess()),
            accessibility=bool(self._AS.AXIsProcessTrusted()),
        )

    def request_permissions(self) -> PermissionStatus:
        status = self.check_permissions()
        if not status.input_monitoring:
            self._Q.CGRequestListenEventAccess()
        if not status.accessibility:
            self._AS.AXIsProcessTrustedWithOptions({self._AS.kAXTrustedCheckOptionPrompt: True})
        return self.check_permissions()

    # ── Event tap ────────────────────────────────────────────────────

    def start(self, out: queue.SimpleQueue) -> bool:
        if self.is_running():
            return True
        self._out = out
        ready = threading.Event()
        result = {"ok": False}
        self._thread = threading.Thread(
            target=self._run_tap, args=(ready, result), name="ui-events-tap", daemon=True,
        )
        self._thread.start()
        ready.wait(timeout=3.0)
        return result["ok"]

    def stop(self) -> None:
        Q = self._Q
        if self._run_loop is not None:
            Q.CFRunLoopStop(self._run_loop)
        if self._thread is not None:
            self._thread.join(timeout=2.0)
        self._thread = None
        self._run_loop = None

    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    def _run_tap(self, ready: threading.Event, result: dict):
        Q = self._Q
        mask = (
            (1 << Q.kCGEventLeftMouseDown)
            | (1 << Q.kCGEventRightMouseDown)
            | (1 << Q.kCGEventKeyDown)
        )
        tap = Q.CGEventTapCreate(
            Q.kCGSessionEventTap,
            Q.kCGTailAppendEventTap,
            Q.kCGEventTapOptionListenOnly,
            mask,
            self._tap_callback,
            None,
        )
        if tap is None:
            logger.warning("CGEventTapCreate failed: Input Monitoring permission is missing")
            ready.set()
            return
        self._tap = tap
        source = Q.CFMachPortCreateRunLoopSource(None, tap, 0)
        self._run_loop = Q.CFRunLoopGetCurrent()
        Q.CFRunLoopAddSource(self._run_loop, source, Q.kCFRunLoopCommonModes)
        Q.CGEventTapEnable(tap, True)
        result["ok"] = True
        ready.set()
        logger.info("Event tap installed")
        try:
            Q.CFRunLoopRun()
        finally:
            Q.CGEventTapEnable(tap, False)
            Q.CFMachPortInvalidate(tap)
            self._tap = None
            logger.info("Event tap removed")

    def _tap_callback(self, proxy, type_, event, refcon):
        Q = self._Q
        try:
            if type_ in (_TAP_DISABLED_BY_TIMEOUT, _TAP_DISABLED_BY_USER_INPUT):
                if self._tap is not None:
                    Q.CGEventTapEnable(self._tap, True)
                return event

            now = time.time()
            if type_ in (Q.kCGEventLeftMouseDown, Q.kCGEventRightMouseDown):
                loc = Q.CGEventGetLocation(event)
                self._out.put(RawEvent(
                    kind="mouse_down", ts=now, x=loc.x, y=loc.y,
                    button="left" if type_ == Q.kCGEventLeftMouseDown else "right",
                ))
            elif type_ == Q.kCGEventKeyDown:
                self._out.put(self._key_event(event, now))
        except Exception:
            # Never raise into the tap; never log here either (too slow).
            pass
        return event

    def _key_event(self, event, now: float) -> RawEvent:
        Q = self._Q
        keycode = Q.CGEventGetIntegerValueField(event, Q.kCGKeyboardEventKeycode)
        flags = Q.CGEventGetFlags(event)
        shortcut = bool(flags & (Q.kCGEventFlagMaskCommand | Q.kCGEventFlagMaskControl))

        key = _KEYCODE_MAP.get(keycode)
        char = None
        if key is None:
            _, chars = Q.CGEventKeyboardGetUnicodeString(event, 4, None, None)
            if chars and chars.isprintable():
                key, char = KEY_CHAR, chars
            else:
                key = KEY_OTHER
        return RawEvent(
            kind="key", ts=now, key=key, char=None if shortcut else char,
            shortcut=shortcut, shortcut_char=(char or "").lower() if shortcut else None,
        )

    # ── Accessibility ────────────────────────────────────────────────

    def _attr(self, element, attr):
        try:
            err, value = self._AS.AXUIElementCopyAttributeValue(element, attr, None)
            return value if err == 0 else None
        except Exception:
            return None

    def _element_pid(self, element) -> Optional[int]:
        try:
            err, pid = self._AS.AXUIElementGetPid(element, None)
            return int(pid) if err == 0 else None
        except Exception:
            return None

    def _element_info(self, element) -> ElementInfo:
        role = self._attr(element, "AXRole")
        subrole = self._attr(element, "AXSubrole")
        is_password = subrole == "AXSecureTextField"
        name = None
        for attr in ("AXTitle", "AXDescription"):
            v = self._attr(element, attr)
            if isinstance(v, str) and v.strip():
                name = v.strip()
                break
        value = None
        if not is_password:
            v = self._attr(element, "AXValue")
            if isinstance(v, str) and v.strip():
                value = v.strip()[:_MAX_VALUE_LEN]
        if name is None and role == "AXStaticText" and value:
            name = value
        if name is None and not is_password:
            # Text inputs usually carry their label as a placeholder.
            v = self._attr(element, "AXPlaceholderValue")
            if isinstance(v, str) and v.strip():
                name = v.strip()
        if name is None and role in _ACTIONABLE_ROLES and role not in _TEXT_INPUT_ROLES:
            name = self._child_label(element) or self._str_attr(element, "AXHelp")
        # A text field's value is the user's own content (a whole document,
        # a draft message). Typing is captured separately; keep it out here.
        if role in _TEXT_INPUT_ROLES or role in _CONTAINER_ROLES:
            value = None
        if name and role in _CONTAINER_ROLES and len(name) > _MAX_CONTAINER_NAME_LEN:
            name = None
        if name and len(name) > _MAX_NAME_LEN:
            name = name[:_MAX_NAME_LEN - 3].rstrip() + "..."
        return ElementInfo(
            role=str(role) if role else None,
            subrole=str(subrole) if subrole else None,
            name=name,
            value=value,
            pid=self._element_pid(element),
            is_password=is_password,
        )

    def _str_attr(self, element, attr) -> Optional[str]:
        v = self._attr(element, attr)
        return v.strip() if isinstance(v, str) and v.strip() else None

    def _child_label(self, element) -> Optional[str]:
        """Web and Electron buttons often keep their label in a child
        AXStaticText or AXImage rather than on the button itself."""
        children = self._attr(element, "AXChildren") or []
        for child in list(children)[:4]:
            role = self._attr(child, "AXRole")
            if role == "AXStaticText":
                label = self._str_attr(child, "AXValue")
            else:
                label = self._str_attr(child, "AXTitle") or self._str_attr(child, "AXDescription")
            if label:
                return label
        return None

    def _enable_manual_a11y(self, pid: Optional[int]):
        """Ask Electron/Chromium apps to expose their full AX tree."""
        from screenmind.platform_support import adapter
        enable = getattr(adapter(), "enable_full_a11y_tree", None)
        if enable:
            enable(pid)

    def element_at(self, x: float, y: float) -> Optional[ElementInfo]:
        try:
            err, element = self._AS.AXUIElementCopyElementAtPosition(self._system_wide, x, y, None)
        except Exception:
            return None
        if err != 0 or element is None:
            return None
        info = self._element_info(element)
        self._enable_manual_a11y(info.pid)
        if info.role in _ACTIONABLE_ROLES:
            return info
        # Clicked a label or icon: walk up to find the control it belongs to.
        parent = element
        for _ in range(3):
            parent = self._attr(parent, "AXParent")
            if parent is None:
                break
            role = self._attr(parent, "AXRole")
            if role in _ACTIONABLE_ROLES:
                p_info = self._element_info(parent)
                if not p_info.name:
                    p_info.name = info.name
                return p_info
        return info

    def focused_element(self) -> Optional[ElementInfo]:
        element = self._attr(self._system_wide, "AXFocusedUIElement")
        if element is None:
            return None
        info = self._element_info(element)
        self._enable_manual_a11y(info.pid)
        return info

    def front_window(self) -> Optional[FrontWindow]:
        from screenmind.platform_support import adapter
        front = adapter().get_front_window()
        if not front:
            return None
        return FrontWindow(pid=front["pid"], app_name=front["app_name"], title=front["title"])

    def app_name_for_pid(self, pid: int) -> Optional[str]:
        try:
            from AppKit import NSRunningApplication  # type: ignore
            app = NSRunningApplication.runningApplicationWithProcessIdentifier_(pid)
            return str(app.localizedName()) if app and app.localizedName() else None
        except Exception:
            return None

    # ── Clipboard ────────────────────────────────────────────────────

    def _pasteboard(self):
        from AppKit import NSPasteboard  # type: ignore
        return NSPasteboard.generalPasteboard()

    def clipboard_change_count(self) -> Optional[int]:
        try:
            return int(self._pasteboard().changeCount())
        except Exception:
            return None

    def read_clipboard(self) -> Optional[str]:
        try:
            from AppKit import NSPasteboardTypeString  # type: ignore
            pb = self._pasteboard()
            types = set(str(t) for t in (pb.types() or []))
            if types & _SECRET_PASTEBOARD_TYPES:
                return None
            text = pb.stringForType_(NSPasteboardTypeString)
            return str(text) if text else None
        except Exception:
            return None
